spring.application.name=SpringEduManager
#puerto por defecto
server.port=8081
#Base Datos
spring.datasource.url=jdbc:mysql://localhost:3306/edumanager
spring.datasource.username=root
spring.datasource.password=admin1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#JPA
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

#Thymeleaf
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.cache=false

 
 #Security
#spring.security.user.name=admin
#spring.security.user.password=admin1234
#spring.security.user.roles=ADMIN

